fonts : font-jetbrains font-meslo
	# The JetBrains font seems to have the best usage/support among the nvim community.
	# All options here:
	#   https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2
	#     ^ You can manually download `JetBrainsMono.zip`, unzip it, then use "Font Book.app" (built-in app) to install it on MacOS
	# Meslo is popular in the zsh community, so I'll add that one too.

font-jetbrains :
	brew tap homebrew/cask-fonts
	brew install font-jetbrains-mono-nerd-font

font-meslo :
	brew tap homebrew/cask-fonts
	brew install font-meslo-lg-nerd-font

.PHONY : fonts font-jetbrains font-meslo
