install :
	pip3 install \
		python-lsp-server pylsp-mypy \
		boto3 pyathena s3fs pyarrow \
		geopandas h3pandas \
		folium contextily \
		moviepy \
		jupyterlab \
		numpy pandas matplotlib

.PHONY : install
