install :
	pip3 install \
		python-lsp-server pylsp-mypy mypy \
		pytest pytest-asyncio \
		boto3 pyathena s3fs pyarrow \
		geopandas h3pandas \
		folium contextily \
		moviepy \
		jupyterlab \
		numpy pandas matplotlib \
		aiohttp[speedups] python-dotenv colorama 

.PHONY : install
