install :
	pip3 install \
		python-lsp-server pylsp-mypy mypy \
		pyright \
		pytest pytest-asyncio \
		hatch \
		jupyterlab \
		numpy pandas matplotlib \
		aiohttp[speedups] python-dotenv colorama

.PHONY : install
